### ISSUE TITLE
get_modules.sh is missing from the repository

### ISSUE THREAD

**Issue by jmceleney** [theforeman/foreman-live#8]
The Readme says that get_modules.sh should be used, but it is not present in the repository.

**Comment by ares** [comment]
this is not needed anymore, when #11 gets merged, the installer will handle modules installation for you

**Comment by mmoll** [comment]
is this still an issue or can it get closed? :)

**Comment by lzap** [comment]
We have redesigned foreman-live, this is not relevant anymore I think. Reopen on need please.
