### ISSUE TITLE
Discovery images referenced do not exist in foreman nightly repo.

### ISSUE THREAD

**Issue by jmceleney** [theforeman/foreman-live#9]
The two discovery files referred to in the kickstart file are not present in the foreman yum repo. The files referenced are:
discovery-prod-0.3.1-1-initrd.img
discovery-prod-0.3.1-1-vmlinuz

The nearest matches are:
foreman-discovery-image-latest.el6.iso-img
foreman-discovery-image-latest.el6.iso-vmlinuz

**Comment by ares** [comment]
will be fixed when #11 is merged, the installer will download correct images

**Comment by mmoll** [comment]
is this still an issue or can it get closed? :)

**Comment by lzap** [comment]
We have redesigned foreman-live, this is not relevant anymore I think. Reopen on need please.
